services:
  - type: web
    name: admission-thesis
    runtime: docker
    plan: free
    region: singapore

    dockerfilePath: ./Dockerfile

    envVars:
      APP_ENV: production
      APP_DEBUG: false
      PORT: 10000

      # Laravel APP KEY (paste your local APP_KEY here)
      APP_KEY: "base64:PASTE_YOUR_KEY_HERE"

      # Database (these will be auto-injected when you create a Render PostgreSQL DB)
      DB_CONNECTION: pgsql
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}

    healthCheckPath: /
